trigger:
- main   # o il nome del tuo branch principale

pool:
  name: Default


steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
  displayName: 'Set up Python'

- script: |
    pip install -r requirements.txt
    python app.py
  displayName: 'Run app.py'
